<span>Quest'opera è pubblicata sotto una licenza 
 <a rel="license" href="http://creativecommons.org/publicdomain/zero/1.0/">Public Domain - CC0</a> pertanto è libera da restrizioni di copyright.
<span/> 
<br/>
<span>Copyleft 2012-<?php echo(date(Y)); ?> 
 <a rel="dct:publisher" href="http://lefontiperlastoria.it/">
  <span property="dct:title">Coop.TeSto</span>
 </a>
</span>

<!--<p xmlns:dct="http://purl.org/dc/terms/" xmlns:vcard="http://www.w3.org/2001/vcard-rdf/3.0#">
  <a rel="license"
     href="http://creativecommons.org/publicdomain/zero/1.0/">
    <img src="http://i.creativecommons.org/p/zero/1.0/88x31.png" style="border-style: none;" alt="CC0" />
  </a>
  <br />
  To the extent possible under law,
  <a rel="dct:publisher"
     href="http://lefontiperlastoria.it/">
    <span property="dct:title">Coop.TeSto</span></a>
  has waived all copyright and related or neighboring rights to
  <span property="dct:title">Le fonti per la storia</span>.
This work is published from:
<span property="vcard:Country" datatype="dct:ISO3166"
      content="IT" about="http://lefontiperlastoria.it/">
  Italia</span>.
</p>-->
